// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWhvl2CgC8ZE-nXVlPNCEsd8VU_cP-Wjs',
    appId: '1:214711529781:web:03d318a276ac16dd415c7c',
    messagingSenderId: '214711529781',
    projectId: 'social-7a36f',
    authDomain: 'social-7a36f.firebaseapp.com',
    storageBucket: 'social-7a36f.appspot.com',
    measurementId: 'G-HEPQQ835BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_quIzPT_3lIrRk7L-SVogxcqr6e4Yqko',
    appId: '1:214711529781:android:cd81bc790ef5a84c415c7c',
    messagingSenderId: '214711529781',
    projectId: 'social-7a36f',
    storageBucket: 'social-7a36f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz-1wVXxJCEqs_u-0BbtPbw8OxgsBmtgk',
    appId: '1:214711529781:ios:41f6465108f9df1f415c7c',
    messagingSenderId: '214711529781',
    projectId: 'social-7a36f',
    storageBucket: 'social-7a36f.appspot.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz-1wVXxJCEqs_u-0BbtPbw8OxgsBmtgk',
    appId: '1:214711529781:ios:051331ac603aebdb415c7c',
    messagingSenderId: '214711529781',
    projectId: 'social-7a36f',
    storageBucket: 'social-7a36f.appspot.com',
    iosBundleId: 'com.example.social.RunnerTests',
  );
}
